/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductIdRouteImport } from './routes/product/$id'
import { Route as ApiShippingQuoteRouteImport } from './routes/api.shipping.quote'
import { Route as ContaPedidosOrderNumberRouteImport } from './routes/conta/pedidos/$orderNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippingQuoteRoute = ApiShippingQuoteRouteImport.update({
  id: '/api/shipping/quote',
  path: '/api/shipping/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPedidosOrderNumberRoute = ContaPedidosOrderNumberRouteImport.update({
  id: '/pedidos/$orderNumber',
  path: '/pedidos/$orderNumber',
  getParentRoute: () => ContaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/cart': typeof CartRoute
  '/conta': typeof ContaRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/product/$id': typeof ProductIdRoute
  '/api/shipping/quote': typeof ApiShippingQuoteRoute
  '/conta/pedidos/$orderNumber': typeof ContaPedidosOrderNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/cart': typeof CartRoute
  '/conta': typeof ContaRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/product/$id': typeof ProductIdRoute
  '/api/shipping/quote': typeof ApiShippingQuoteRoute
  '/conta/pedidos/$orderNumber': typeof ContaPedidosOrderNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/cart': typeof CartRoute
  '/conta': typeof ContaRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/product/$id': typeof ProductIdRoute
  '/api/shipping/quote': typeof ApiShippingQuoteRoute
  '/conta/pedidos/$orderNumber': typeof ContaPedidosOrderNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/cart'
    | '/conta'
    | '/login'
    | '/products'
    | '/product/$id'
    | '/api/shipping/quote'
    | '/conta/pedidos/$orderNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/cart'
    | '/conta'
    | '/login'
    | '/products'
    | '/product/$id'
    | '/api/shipping/quote'
    | '/conta/pedidos/$orderNumber'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/cart'
    | '/conta'
    | '/login'
    | '/products'
    | '/product/$id'
    | '/api/shipping/quote'
    | '/conta/pedidos/$orderNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRoute
  CartRoute: typeof CartRoute
  ContaRoute: typeof ContaRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiShippingQuoteRoute: typeof ApiShippingQuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipping/quote': {
      id: '/api/shipping/quote'
      path: '/api/shipping/quote'
      fullPath: '/api/shipping/quote'
      preLoaderRoute: typeof ApiShippingQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/pedidos/$orderNumber': {
      id: '/conta/pedidos/$orderNumber'
      path: '/pedidos/$orderNumber'
      fullPath: '/conta/pedidos/$orderNumber'
      preLoaderRoute: typeof ContaPedidosOrderNumberRouteImport
      parentRoute: typeof ContaRoute
    }
  }
}

interface ContaRouteChildren {
  ContaPedidosOrderNumberRoute: typeof ContaPedidosOrderNumberRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaPedidosOrderNumberRoute: ContaPedidosOrderNumberRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRoute,
  CartRoute: CartRoute,
  ContaRoute: ContaRouteWithChildren,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ProductIdRoute: ProductIdRoute,
  ApiShippingQuoteRoute: ApiShippingQuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
