-- BIGofertas
-- FASE 07
-- Pool automatico de identificadores de produto
--
-- Objetivos:
-- 1. SKU, slug e SKU da variante padrao nao sao digitados pelo administrador.
-- 2. O banco mantem um estoque de identificadores livres para produtos futuros.
-- 3. Ao criar um produto, uma reserva e consumida automaticamente.
-- 4. Nenhum produto ficticio e criado apenas para reservar identificadores.

BEGIN;

CREATE SEQUENCE IF NOT EXISTS public.product_identity_number_seq
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NO MAXVALUE
  CACHE 20;

CREATE TABLE IF NOT EXISTS public.product_identity_slots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_number bigint NOT NULL UNIQUE,
  product_sku text NOT NULL UNIQUE,
  product_slug text NOT NULL UNIQUE,
  default_variant_sku text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'available',
  reserved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  reserved_at timestamptz,
  claimed_product_id uuid UNIQUE REFERENCES public.products(id) ON DELETE SET NULL,
  claimed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT product_identity_slots_status_valid
    CHECK (status IN ('available', 'reserved', 'claimed')),
  CONSTRAINT product_identity_slots_product_sku_format
    CHECK (product_sku ~ '^BIG-P[0-9]{6,}$'),
  CONSTRAINT product_identity_slots_slug_format
    CHECK (product_slug ~ '^produto-[0-9]{6,}$'),
  CONSTRAINT product_identity_slots_variant_sku_format
    CHECK (default_variant_sku ~ '^BIG-P[0-9]{6,}-STD$')
);

CREATE INDEX IF NOT EXISTS product_identity_slots_status_idx
  ON public.product_identity_slots (status, serial_number);

ALTER TABLE public.product_identity_slots ENABLE ROW LEVEL SECURITY;

-- A tabela nao possui policies de escrita/leitura pelo frontend.
-- O acesso ocorre exclusivamente pelas funcoes SECURITY DEFINER abaixo.
REVOKE ALL ON TABLE public.product_identity_slots FROM PUBLIC;
REVOKE ALL ON TABLE public.product_identity_slots FROM anon;
REVOKE ALL ON TABLE public.product_identity_slots FROM authenticated;

CREATE OR REPLACE FUNCTION public.ensure_product_identity_pool(
  target_available integer DEFAULT 20
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  available_count integer;
  missing_count integer;
  sequence_number bigint;
  candidate_product_sku text;
  candidate_product_slug text;
  candidate_variant_sku text;
  i integer;
BEGIN
  IF target_available < 1 OR target_available > 200 THEN
    RAISE EXCEPTION 'Quantidade alvo de reservas invalida: %', target_available;
  END IF;

  SELECT count(*)::integer
  INTO available_count
  FROM public.product_identity_slots s
  WHERE s.status = 'available'
    AND NOT EXISTS (
      SELECT 1
      FROM public.products p
      WHERE lower(p.sku) = lower(s.product_sku)
         OR p.slug = s.product_slug
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.product_variants v
      WHERE lower(v.sku) = lower(s.default_variant_sku)
    );

  missing_count := GREATEST(target_available - available_count, 0);

  IF missing_count = 0 THEN
    RETURN;
  END IF;

  FOR i IN 1..missing_count LOOP
    LOOP
      sequence_number := nextval('public.product_identity_number_seq');
      candidate_product_sku := 'BIG-P' || lpad(sequence_number::text, 6, '0');
      candidate_product_slug := 'produto-' || lpad(sequence_number::text, 6, '0');
      candidate_variant_sku := candidate_product_sku || '-STD';

      EXIT WHEN NOT EXISTS (
        SELECT 1
        FROM public.product_identity_slots s
        WHERE lower(s.product_sku) = lower(candidate_product_sku)
           OR s.product_slug = candidate_product_slug
           OR lower(s.default_variant_sku) = lower(candidate_variant_sku)
      )
      AND NOT EXISTS (
        SELECT 1
        FROM public.products p
        WHERE lower(p.sku) = lower(candidate_product_sku)
           OR p.slug = candidate_product_slug
      )
      AND NOT EXISTS (
        SELECT 1
        FROM public.product_variants v
        WHERE lower(v.sku) = lower(candidate_variant_sku)
      );
    END LOOP;

    INSERT INTO public.product_identity_slots (
      serial_number,
      product_sku,
      product_slug,
      default_variant_sku,
      status
    )
    VALUES (
      sequence_number,
      candidate_product_sku,
      candidate_product_slug,
      candidate_variant_sku,
      'available'
    );
  END LOOP;
END;
$$;

REVOKE ALL
ON FUNCTION public.ensure_product_identity_pool(integer)
FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.allocate_product_identity()
RETURNS TABLE (
  reservation_id bigint,
  product_sku text,
  product_slug text,
  default_variant_sku text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  selected_slot public.product_identity_slots%ROWTYPE;
BEGIN
  IF NOT public.has_role('owner'::public.app_role) THEN
    RAISE EXCEPTION 'Permissao insuficiente para reservar identificadores';
  END IF;

  -- Reservas abandonadas antes da criacao do produto voltam ao pool.
  UPDATE public.product_identity_slots
  SET
    status = 'available',
    reserved_by = NULL,
    reserved_at = NULL
  WHERE status = 'reserved'
    AND claimed_product_id IS NULL
    AND reserved_at < now() - interval '30 minutes';

  PERFORM public.ensure_product_identity_pool(20);

  SELECT s.*
  INTO selected_slot
  FROM public.product_identity_slots s
  WHERE s.status = 'available'
    AND NOT EXISTS (
      SELECT 1
      FROM public.products p
      WHERE lower(p.sku) = lower(s.product_sku)
         OR p.slug = s.product_slug
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.product_variants v
      WHERE lower(v.sku) = lower(s.default_variant_sku)
    )
  ORDER BY s.serial_number
  FOR UPDATE SKIP LOCKED
  LIMIT 1;

  IF selected_slot.id IS NULL THEN
    RAISE EXCEPTION 'Nao ha identificadores de produto disponiveis';
  END IF;

  UPDATE public.product_identity_slots
  SET
    status = 'reserved',
    reserved_by = auth.uid(),
    reserved_at = now()
  WHERE id = selected_slot.id;

  -- Reposicao imediata: depois de consumir uma reserva, mantemos outras 20 livres.
  PERFORM public.ensure_product_identity_pool(20);

  reservation_id := selected_slot.id;
  product_sku := selected_slot.product_sku;
  product_slug := selected_slot.product_slug;
  default_variant_sku := selected_slot.default_variant_sku;
  RETURN NEXT;
END;
$$;

REVOKE ALL
ON FUNCTION public.allocate_product_identity()
FROM PUBLIC, anon;

GRANT EXECUTE
ON FUNCTION public.allocate_product_identity()
TO authenticated;

CREATE OR REPLACE FUNCTION public.claim_product_identity_after_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.product_identity_slots
  SET
    status = 'claimed',
    claimed_product_id = NEW.id,
    claimed_at = now()
  WHERE lower(product_sku) = lower(NEW.sku)
    AND status = 'reserved'
    AND reserved_by = auth.uid();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS claim_product_identity_after_insert
ON public.products;

CREATE TRIGGER claim_product_identity_after_insert
AFTER INSERT ON public.products
FOR EACH ROW
EXECUTE FUNCTION public.claim_product_identity_after_insert();

CREATE OR REPLACE FUNCTION public.release_product_identity(
  target_reservation_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NOT public.has_role('owner'::public.app_role) THEN
    RAISE EXCEPTION 'Permissao insuficiente para liberar identificadores';
  END IF;

  UPDATE public.product_identity_slots
  SET
    status = 'available',
    reserved_by = NULL,
    reserved_at = NULL,
    claimed_product_id = NULL,
    claimed_at = NULL
  WHERE id = target_reservation_id
    AND reserved_by = auth.uid()
    AND claimed_product_id IS NULL
    AND status IN ('reserved', 'claimed');

  PERFORM public.ensure_product_identity_pool(20);
END;
$$;

REVOKE ALL
ON FUNCTION public.release_product_identity(bigint)
FROM PUBLIC, anon;

GRANT EXECUTE
ON FUNCTION public.release_product_identity(bigint)
TO authenticated;

-- Cria o estoque inicial de 20 reservas sem criar produtos artificiais.
SELECT public.ensure_product_identity_pool(20);

COMMIT;
